plugins:
  topic_custom_field_enabled:
    default: true
    client: true
  topic_custom_field_name:
    default: 'price'
    client: true
  topic_custom_field_type:
    default: 'integer'
    client: true
    type: enum
    choices:
      - string
      - integer
      - boolean
      - json